#! /usr/bin/env node

const groups = [
	[ 0,  1,  2],
	[ 3,  4,  5],
	[ 6,  7,  8],
	[ 9, 10, 11],
	[12, 13, 14],
	[15, 16, 17],
]

const trials = groups.flatMap(
	([x, y, z]) => [
		[x,y],
		[x,y],
		[x,y],
		[x,z],
		[x,z],
		[x,z],
		[y,z],
		[y,z],
		[y,z],
	],
)

const shuffle = arr => {
	for (let i = arr.length - 1; i > 0; i--) {
		const j = Math.floor(Math.random() * (i + 1))
		;[arr[i], arr[j]] = [arr[j], arr[i]]
	}
	return arr
}

for (let i = 0; i < 1e5; i++) {
	shuffle(trials)
}

console.log(trials)
